# -*- coding: utf-8 -*-

# --- Übersetzungsdaten ---
# Enthält Texte für verschiedene UI-Elemente in unterstützten Sprachen.
# Schlüssel werden im Code verwendet (z.B. t.get('app_title')), der Wert ist der angezeigte Text.
translations = {
    'DE': {
        # App Allgemein
        "app_title": "Advanced DSO Finder",
        "lang_select": "Sprache wählen",
        "settings_header": "Einstellungen",
        "bug_report": "Fehler gefunden oder Feedback?",
        "bug_report_button": "🐞 Problem melden / Vorschlag machen",
        "bug_report_subject": "Bug Report/Feedback: Advanced DSO Finder",
        "bug_report_body": "Bitte beschreiben Sie das Problem oder den Vorschlag:\n\n(Bei Fehlern bitte Schritte zur Reproduktion angeben)\n\nApp Version/Datum: [Falls bekannt]\nBrowser/OS: [Falls relevant]",
        "error_module_missing": "Fehler: Modul fehlt:", # Wird mit Modulnamen ergänzt
        "error_unexpected": "Unerwarteter Fehler:", # Wird mit Fehlermeldung ergänzt

        # Katalog & Laden
        "info_catalog_loaded": "Katalog geladen: {} Objekte.",
        "error_catalog_load_failed": "Katalog konnte nicht geladen werden. Datei prüfen.",
        "error_catalog_not_found": "Fehler: Katalogdatei nicht gefunden unter Pfad:", # Wird mit Pfad ergänzt
        "info_catalog_missing": "Katalogdaten konnten nicht geladen werden. Suche deaktiviert.",

        # Glossar
        "object_type_glossary_title": "Objekttyp Glossar",
        "glossary_unavailable": "Glossar nicht verfügbar für die gewählte Sprache.",
        "object_type_glossary": {
            # Glossareinträge hier hinzufügen (Beispiele)
            "G": "Galaxie",
            "OC": "Offener Sternhaufen (Open Cluster)",
            "GC": "Kugelsternhaufen (Globular Cluster)",
            "PN": "Planetarischer Nebel (Planetary Nebula)",
            "DN": "Dunkelnebel (Dark Nebula)",
            "BN": "Heller Nebel (Bright Nebula)",
            "SNR": "Supernova-Überrest (Supernova Remnant)",
            "C+N": "Nebel mit eingebettetem Haufen",
            "Ast": "Asterismus",
            "Kt": "Knoten in Galaxie",
            "Dup": "Duplikat",
            "NonEx": "Nicht existent",
            # ... weitere Typen aus ONGC ...
        },

        # Standort Einstellungen
        "location_expander": "📍 Standort",
        "location_select_label": "Standortmethode",
        "location_option_search": "Suche",
        "location_option_manual": "Manuell",
        "location_lat_label": "Breite (°N)",
        "location_lon_label": "Länge (°E)",
        "location_elev_label": "Höhe (m)",
        "location_error_manual_invalid": "Manuelle Koordinaten oder Höhe ungültig.",
        "location_search_label": "Ort/Adresse suchen:",
        "location_search_placeholder": "z.B. Berlin, Deutschland oder PLZ",
        "location_search_submit_button": "Koordinaten finden",
        "spinner_geocoding": "Suche Standort...",
        "location_search_info_fallback": "Nominatim fehlgeschlagen, versuche ArcGIS...",
        "location_search_info_fallback2": "ArcGIS fehlgeschlagen, versuche Photon...",
        "location_search_coords": "Lat:{:.4f}, Lon:{:.4f}",
        "location_search_found": "Gefunden (N): {}", # N für Nominatim
        "location_search_found_fallback": "Gefunden (A): {}", # A für ArcGIS
        "location_search_found_fallback2": "Gefunden (P): {}", # P für Photon
        "location_search_error_timeout": "Zeitüberschreitung bei Geocoding.",
        "location_search_error_service": "Geocoding Dienstfehler: {}",
        "location_search_error_fallback2_failed": "Alle Geocoding Dienste fehlgeschlagen: {}",
        "location_search_error_not_found": "Standort nicht gefunden.",
        "timezone_auto_set_label": "Erkannte Zeitzone:",
        "timezone_auto_fail_label": "Zeitzone:",
        "timezone_auto_fail_msg": "Erkennung fehlgeschlagen",
        "timezone_auto_fail_invalid_label": "Zeitzone:",
        "timezone_auto_fail_invalid_msg": "Ungültiger Name:",
        "timezone_auto_fail_error_label": "Zeitzone:",
        "timezone_auto_fail_error_msg": "Fehler",
        "timezone_finder_unavailable_label": "Zeitzone:",
        "timezone_finder_unavailable_msg": "Finder n.v.",
        "timezone_invalid_location_label": "Zeitzone:",
        "timezone_invalid_location_msg": "Standort ungültig",
        "location_not_set": "Standort nicht gesetzt oder ungültig.",
        "location_manual_display": "Manuell ({:.4f}°N, {:.4f}°E)",
        "location_search_display": "Gesucht: {} ({:.4f}°N, {:.4f}°E)",
        "location_invalid_for_run": "Standort ungültig",
        "error_observer_creation": "Fehler beim Erstellen des Beobachterstandorts: {}",

        # Zeit Einstellungen
        "time_expander": "⏱️ Zeit",
        "time_select_label": "Zeitrahmen wählen",
        "time_option_now": "Jetzt",
        "time_option_specific": "Spezifische Nacht",
        "time_date_select_label": "Datum für Nacht wählen:",
        "error_ref_time_creation": "Fehler beim Setzen der Referenzzeit: {}",
        "info_set_ref_time": "Bitte gültiges Datum sicherstellen.",

        # Filter Einstellungen
        "filters_expander": "✨ Filter",
        "mag_filter_header": "**Magnitude**",
        "mag_filter_option_bortle": "Bortle Skala",
        "mag_filter_option_manual": "Manuell",
        "mag_filter_method_label": "Filter Methode:",
        "mag_filter_bortle_label": "Bortle Skala:",
        "mag_filter_bortle_help": "Bortle Klasse wählen (1=dunkel, 9=Stadt)",
        "mag_filter_min_mag_label": "Min Magnitude:",
        "mag_filter_min_mag_help": "Hellste Magnitude (kleinere Zahlen = heller)",
        "mag_filter_max_mag_label": "Max Magnitude:",
        "mag_filter_max_mag_help": "Schwächste Magnitude (größere Zahlen = schwächer)",
        "mag_filter_warning_min_max": "Minimum Magnitude darf nicht größer als Maximum sein!",
        "min_alt_header": "**Höhe**",
        "min_alt_label": "Minimale Höhe (°):",
        "min_alt_help": "Objekte müssen über dieser Höhe sein.",
        "max_alt_label": "Maximale Höhe (°):",
        "max_alt_help": "Objekte müssen unter dieser Höhe sein (für Hindernisse).",
        "alt_filter_warning_min_max": "Minimale Höhe darf nicht größer als Maximale sein!",
        "moon_warning_header": "**Mond**",
        "moon_warning_label": "Warnen wenn Mond > (%):",
        "moon_warning_help": "Zeige Warnung in Ergebnissen, wenn Mond heller ist.",
        "object_types_header": "**Objekttypen**",
        "object_types_warning_missing_column": "Katalog fehlt Spalte 'Type'.",
        "object_types_error_extract": "Fehler beim Extrahieren der Typen",
        "object_types_label": "Nach Objekttyp(en) filtern:",
        "object_types_help": "Spezifische Typen wählen (leer lassen für alle).",
        "object_types_info_no_types": "Keine Objekttypen im Katalog verfügbar. Filter deaktiviert.",
        "size_filter_header": "**Scheinbare Größe**",
        "size_filter_label": "Größenbereich (Arcmin):",
        "size_filter_help": "Filter nach scheinbarer Größe der Hauptachse.",
        "size_filter_error": "Fehler beim Einrichten des Größen-Sliders",
        "size_filter_info_missing": "Größen-Daten ('MajAx') fehlen. Filter deaktiviert.",
        "direction_filter_header": "**Kulminationsrichtung**",
        "direction_option_all": "Alle Richtungen",
        "direction_filter_label": "Nach Richtung bei max. Höhe filtern:",
        "direction_filter_help": "Zeige nur Objekte, die in der gewählten Richtung kulminieren.",

        # Ergebnisoptionen
        "results_options_expander": "⚙️ Ergebnisoptionen",
        "results_options_max_objects_label": "Max. anzuzeigende Objekte:",
        "results_options_max_objects_help": "Begrenzt die Anzahl der Objekte in der Ergebnisliste.",
        "results_options_sort_method_label": "Ergebnisse sortieren nach:",
        "results_options_sort_duration": "Dauer & Höhe",
        "results_options_sort_magnitude": "Helligkeit (Magnitude)",
        "results_options_sort_method_help": "Wählt die Sortierreihenfolge der gefundenen Objekte.",

        # Hauptbereich: Parameters & Suche
        "search_params_header": "Zusammenfassung Suchparameter",
        "search_params_location_label": "Standort:",
        "search_params_time_label": "Zeit:",
        "search_params_time_now": "Jetzt (Lokal: {} {})",
        "search_params_time_now_utc": "Jetzt (UTC: {})",
        "search_params_time_specific": "Nacht vom {}",
        "search_params_filter_mag_label": "Magnitude:",
        "search_params_filter_mag_bortle": "Bortle {} (≤ Mag {:.1f})",
        "search_params_filter_mag_bortle_error": "Bortle {} (Limit Fehler)",
        "search_params_filter_mag_manual": "Manuell (Mag {:.1f} bis {:.1f})",
        "search_params_filter_alt_label": "Höhe:",
        "search_params_filter_alt_types": "🔭 Höhe:{}-{}°, Typ:{}", # Kombiniert für Kompaktheit
        "search_params_filter_type_label": "Typen:",
        "search_params_types_all": "Alle",
        "search_params_filter_size_label": "Größe:",
        "search_params_filter_size": "📐 Größe:{:.1f}′ – {:.1f}′", # Kombiniert
        "search_params_filter_direction_label": "Kulm. Richtung:",
        "search_params_direction_all": "Alle",
        "search_params_filter_direction": "🧭 Richtung@Max: {}", # Kombiniert

        "find_button_label": "🔭 Beobachtbare Objekte finden",
        "info_initial_prompt": "Bitte gültigen Standort in der Sidebar setzen, um Suche zu ermöglichen.",
        "spinner_searching": "Suche beobachtbare Objekte...",
        # --- Korrektur: Keyword-Platzhalter verwenden ---
        "error_window_unexpected": "Unerwarteter Fehler bei Fensterberechnung: {e}", # Beispiel mit Keyword
        "info_window_calculated": "Beobachtungsfenster: {start_utc} bis {end_utc} UTC",
        "info_window_polar_day": "Kein dunkles Fenster gefunden (Polartag?).", # Keine Platzhalter benötigt
        "info_window_polar_night": "Kein klares Fenster gefunden (Polarnacht?).", # Keine Platzhalter benötigt
        "info_window_polar_night_full": "Dauerhaft dunkel im Fenster: {start_utc} bis {end_utc} UTC",
        "info_window_polar_night_start": "Fenster: {start_utc} bis {end_utc} UTC (Polarnacht beginnt)",
        "info_window_polar_day_end": "Fenster: {start_utc} bis {end_utc} UTC (Polartag endet)",
        "error_no_window": "Kein gültiges Beobachtungsfenster gefunden.", # Keine Platzhalter benötigt
        # --- Ende Korrektur ---
        "error_cannot_search_no_window": "Suche ohne gültiges Beobachtungsfenster nicht möglich.",
        "warning_window_too_short": "Beobachtungsfenster sehr kurz, Ergebnisse evtl. limitiert.",
        "warning_window_too_short_calc": "Beobachtungsfenster sehr kurz. Ergebnisse basieren auf wenigen Zeitpunkten.",
        "warning_no_objects_after_filters": "Keine Objekte entsprechen den Magnitude-, Typ- oder Größenfiltern.",
        "warning_no_objects_found_final": "Keine Objekte gefunden, die allen Kriterien entsprechen (inkl. Höhe/Richtung).",
        "success_objects_found": "{} Objekte gefunden, die Kriterien entsprechen.", # OK mit positional
        "info_showing_list_duration": "Zeige Top {} Ergebnisse (sortiert nach Dauer & Höhe).", # OK mit positional
        "info_showing_list_magnitude": "Zeige Top {} Ergebnisse (sortiert nach Helligkeit).", # OK mit positional
        "error_search_unexpected": "Unerwarteter Fehler während der Suche:",
        "error_prereq_catalog": "Fehler: Katalogdaten nicht geladen.",
        "error_prereq_location": "Fehler: Standort ungültig.",
        "error_prereq_time": "Fehler: Referenzzeit ungültig.",
        "info_no_results_to_display": "Keine Ergebnisse zum Anzeigen.",

        # Ergebnisliste & Details
        "results_list_header": "Ergebnisse",
        "moon_metric_label": "Mondbeleuchtung",
        "moon_warning_message": "Warnung: Mond ({:.0f}%) heller als Schwelle ({}%)!", # OK mit positional
        "moon_phase_error": "Mondphase konnte nicht berechnet werden: {}", # OK mit positional
        "moon_phase_info_cannot_calc": "Mondphasenberechnung benötigt gültigen Standort und Zeitfenster.",
        "graph_type_label": "Plot-Typ wählen:",
        "graph_type_sky_path": "Himmelspfad (Polar)",
        "graph_type_alt_time": "Höhe vs. Zeit",
        "results_expander_title": "{} ({}) - Mag: {}", # OK mit positional
        "magnitude_unknown": "k.A.",
        "results_details_header": "Details:",
        "results_size_label": "Größe:",
        "results_size_value": "{:.1f}′", # OK mit positional
        "results_max_alt_header": "Max. Höhe:",
        "results_azimuth_label": "(Az:{:.1f}°)", # OK mit positional
        "results_direction_label": ", Dir:{}", # OK mit positional
        "results_best_time_header": "Beste Zeit (Lokal):",
        "results_cont_duration_header": "Max. kont. Dauer:",
        "results_duration_value": "{:.1f} Stunden", # OK mit positional
        "google_link_text": "Google",
        "simbad_link_text": "SIMBAD",
        "results_graph_button": "📈 Plot",
        "results_spinner_plotting": "Erstelle Plot...",
        "results_close_graph_button": "Plot schließen",
        "results_graph_not_created": "Plot konnte nicht erstellt werden.",
        "results_save_csv_button": "💾 Ergebnisse als CSV speichern",
        "results_csv_filename": "dso_ergebnisse_{}.csv", # OK mit positional
        "results_csv_export_error": "Fehler beim Erstellen der CSV-Datei: {}", # OK mit positional
        "results_export_name": "Name",
        "results_export_type": "Typ",
        "results_export_constellation": "Sternbild",
        "results_export_mag": "Magnitude",
        "results_export_size": "Größe (arcmin)",
        "results_export_ra": "RA",
        "results_export_dec": "Dec",
        "results_export_max_alt": "Max Höhe (°)",
        "results_export_az_at_max": "Azimut bei Max (°)",
        "results_export_direction_at_max": "Richtung bei Max",
        "results_export_time_max_utc": "Zeit bei Max (UTC)",
        "results_export_time_max_local": "Zeit bei Max (Lokal)",
        "results_export_cont_duration": "Max kont. Dauer (h)",
        "results_export_redshift": "Rotverschiebung (z)", # Für CSV hinzugefügt

        # Plotting Fehler/Infos
        "plot_error_invalid_data_type": "Plot Fehler: Ungültiger plot_data Typ.",
        "plot_object_default_name": "Objekt",
        "plot_error_missing_time_alt": "Plot Fehler: Fehlende oder ungültige Zeit/Höhen-Daten.",
        "plot_error_missing_azimuth": "Plot Fehler: Fehlende Azimut-Daten für Himmelspfad.",
        "plot_error_mismatched_lengths": "Plot Fehler: Zeit-, Höhen- und Azimut-Arrays haben unterschiedliche Längen.",
        "plot_error_no_data_points": "Plot Fehler: Nicht genügend Datenpunkte zum Plotten.",
        "graph_min_altitude_label": "Min Höhe ({:.0f}°)", # OK mit positional
        "graph_max_altitude_label": "Max Höhe ({:.0f}°)", # OK mit positional
        "graph_xlabel_time": "Zeit (UTC)",
        "graph_ylabel_alt": "Höhe (°)",
        "graph_title_alt_time": "Höhe vs. Zeit: {}", # OK mit positional
        "graph_title_sky_path": "Himmelspfad: {}", # OK mit positional
        "graph_colorbar_label": "Zeit (UTC)",
        "plot_error_unknown_type": "Plot Fehler: Unbekannter Plot-Typ: '{}'", # OK mit positional
        "plot_error_unexpected": "Plot Fehler: Unerwarteter Fehler bei Plot-Erstellung: {}", # OK mit positional

        # Custom Target Section
        "custom_target_expander": "Eigenes RA/Dec Ziel plotten",
        "custom_target_ra_label": "Rektaszension (RA):",
        "custom_target_ra_placeholder": "z.B. 10h 08m 22.3s oder 10.1395h",
        "custom_target_dec_label": "Deklination (Dec):",
        "custom_target_dec_placeholder": "z.B. +11d 58m 02s oder 11.9672d",
        "custom_target_name_label": "Zielname (Optional):",
        "custom_target_name_default_placeholder": "Eigenes Ziel",
        "custom_target_name_default": "Eigenes Ziel",
        "custom_target_button": "Eigenes Ziel plotten",
        "custom_target_error_coords_missing": "RA und Dec Koordinaten benötigt.",
        "custom_target_error_window_invalid": "Gültiger Standort und Beobachtungsfenster benötigt (erst Suche durchführen).",
        "custom_target_error_window_order": "Fenster-Startzeit muss vor Endzeit liegen.",
        "custom_target_error_window_short": "Beobachtungsfenster zu kurz zum Plotten.",
        "custom_target_error_parsing": "Fehler beim Parsen der Koordinaten:",
        "custom_target_error_unexpected": "Unerwarteter Fehler beim Plotten:",

        # Kosmologie (aus Redshift Calculator und erweitert)
        "manual_cosmology_expander": "🌌 Manueller Kosmologie-Rechner", # Für manuellen Rechner
        "results_cosmology_button": "🌌 Kosmologie",
        "cosmology_results_header": "Kosmologische Daten",
        "cosmology_not_applicable": "Kosmologische Daten nicht anwendbar für z ≤ 0.",
        "cosmology_invalid_z": "Ungültiger Rotverschiebungswert im Katalog.",
        "error_module_missing_cosmo": "Fehler: Funktion 'calculate_lcdm_distances' nicht in 'astro_calculations' gefunden.",
        "error_calc_failed_cosmo": "Kosmologie-Berechnung fehlgeschlagen",
        "redshift_z": "Rotverschiebung (z)",
        "redshift_z_tooltip": "Kosmologische Rotverschiebung eingeben.",
        "cosmo_params": "Kosmologische Parameter",
        "hubble_h0": "Hubble-Konstante (H₀) [km/s/Mpc]",
        "omega_m": "Materiedichte (Ωm)",
        "omega_lambda": "Dunkle Energie (ΩΛ)",
        "flat_universe_warning": "Ωm + ΩΛ ≉ 1. Berechnungen gehen von flachem Universum aus (Ωk=0).",
        "results_for": "Ergebnisse für z = {z:.5f}", # OK with keyword
        "error_invalid_input": "Ungültige Eingabe. Bitte Zahlen verwenden.",
        "error_h0_positive": "Hubble-Konstante muss positiv sein.",
        "error_omega_negative": "Omega-Parameter dürfen nicht negativ sein.",
        "warn_blueshift": "Warnung: Rotverschiebung negativ (Blueshift). Kosmologische Distanzen sind 0 oder nicht direkt anwendbar.",
        "error_dep_scipy": "Abhängigkeit 'scipy' nicht gefunden. Bitte installieren.",
        "error_calc_failed": "Berechnung fehlgeschlagen: {e}", # OK with keyword
        "warn_integration_accuracy": "Warnung: Relative Integrationsgenauigkeit evtl. nicht erreicht (Fehler: DC={err_dc:.2e}, LT={err_lt:.2e}).", # OK with keywords
        "lookback_time": "Rückblickzeit",
        "cosmo_distances": "Kosmologische Distanzen",
        "comoving_distance_title": "**Mitbewegte Distanz:**",
        "luminosity_distance_title": "**Leuchtkraftdistanz:**",
        "angular_diameter_distance_title": "**Winkeldurchmesserdistanz:**",
        "unit_Gyr": "Gyr (Mrd. Jahre)",
        "unit_Mpc": "Mpc",
        "unit_Gly": "Gly (Mrd. Lichtjahre)",
        "unit_km": "km",
        "unit_km_sci": "km (wiss.)",
        "unit_km_full": "km (ausgeschr.)",
        "unit_LJ": "LJ",
        "unit_AE": "AE",
        "unit_Ls": "Ls",
        "calculation_note": "Berechnung basiert auf flachem ΛCDM-Modell (Strahlung vernachlässigt).",
        "example_lookback_recent": "Vor Kurzem (kosmologisch).",
        "example_lookback_humans": "Entwicklung moderner Menschen.",
        "example_lookback_dinos": "Zeitalter der Dinosaurier.",
        "example_lookback_multicellular": "Entstehung komplexen Lebens.",
        "example_lookback_earth": "Entstehung der Erde.",
        "example_lookback_early_univ": "Frühes Universum.",
        "example_comoving_local": "Lokale Galaxiengruppe.",
        "example_comoving_virgo": "Virgo-Galaxienhaufen.",
        "example_comoving_coma": "Coma-Galaxienhaufen.",
        "example_comoving_lss": "Großräumige Strukturen.",
        "example_comoving_quasars": "Ferne Quasare.",
        "example_comoving_cmb": "'Rand' des beob. Universums (CMB).",
        "explanation_luminosity": "Relevant für Helligkeit (Standardkerzen).",
        "explanation_angular": "Relevant für Größe (Standardlineale).",

        # Donation Link
        "donation_button_text": "Entwicklung unterstützen via Ko-fi ☕",
    },
    # --- Englische Übersetzungen ---
    'EN': {
        # App General
        "app_title": "Advanced DSO Finder",
        "lang_select": "Select Language",
        "settings_header": "Settings",
        "bug_report": "Found a bug or have feedback?",
        "bug_report_button": "🐞 Report Issue / Suggestion",
        "bug_report_subject": "Bug Report/Feedback: Advanced DSO Finder",
        "bug_report_body": "Please describe the issue or suggestion:\n\n(Include steps to reproduce if reporting a bug)\n\nApp Version/Date: [If known]\nBrowser/OS: [If relevant]",
        "error_module_missing": "Error: Module missing:",
        "error_unexpected": "Unexpected Error:",

        # Catalog & Loading
        "info_catalog_loaded": "Catalog loaded: {} objects.",
        "error_catalog_load_failed": "Catalog loading failed. Check file.",
        "error_catalog_not_found": "Error: Catalog file not found at path:",
        "info_catalog_missing": "Catalog data could not be loaded. Search disabled.",

        # Glossary
        "object_type_glossary_title": "Object Type Glossary",
        "glossary_unavailable": "Glossary not available for the selected language.",
        "object_type_glossary": {
            "G": "Galaxy", "OC": "Open Cluster", "GC": "Globular Cluster", "PN": "Planetary Nebula",
            "DN": "Dark Nebula", "BN": "Bright Nebula", "SNR": "Supernova Remnant", "C+N": "Cluster with Nebula",
            "Ast": "Asterism", "Kt": "Knot in Galaxy", "Dup": "Duplicate", "NonEx": "Non-Existent",
        },

        # Location Settings
        "location_expander": "📍 Location",
        "location_select_label": "Location Method",
        "location_option_search": "Search",
        "location_option_manual": "Manual",
        "location_lat_label": "Latitude (°N)",
        "location_lon_label": "Longitude (°E)",
        "location_elev_label": "Elevation (m)",
        "location_error_manual_invalid": "Manual coordinate or elevation fields are invalid.",
        "location_search_label": "Search Location/Address:",
        "location_search_placeholder": "e.g., Paris, France or Zip Code",
        "location_search_submit_button": "Find Coordinates",
        "spinner_geocoding": "Searching for location...",
        "location_search_info_fallback": "Nominatim failed, trying ArcGIS...",
        "location_search_info_fallback2": "ArcGIS failed, trying Photon...",
        "location_search_coords": "Lat:{:.4f}, Lon:{:.4f}",
        "location_search_found": "Found (N): {}",
        "location_search_found_fallback": "Found (A): {}",
        "location_search_found_fallback2": "Found (P): {}",
        "location_search_error_timeout": "Geocoding timed out.",
        "location_search_error_service": "Geocoding service error: {}",
        "location_search_error_fallback2_failed": "All geocoding services failed: {}",
        "location_search_error_not_found": "Location not found.",
        "timezone_auto_set_label": "Detected Timezone:",
        "timezone_auto_fail_label": "Timezone:",
        "timezone_auto_fail_msg": "Detection failed",
        "timezone_auto_fail_invalid_label": "Timezone:",
        "timezone_auto_fail_invalid_msg": "Invalid Name:",
        "timezone_auto_fail_error_label": "Timezone:",
        "timezone_auto_fail_error_msg": "Error",
        "timezone_finder_unavailable_label": "Timezone:",
        "timezone_finder_unavailable_msg": "Finder N/A",
        "timezone_invalid_location_label": "Timezone:",
        "timezone_invalid_location_msg": "Location Invalid",
        "location_not_set": "Location not set or invalid.",
        "location_manual_display": "Manual ({:.4f}°N, {:.4f}°E)",
        "location_search_display": "Searched: {} ({:.4f}°N, {:.4f}°E)",
        "location_invalid_for_run": "Location Invalid",
        "error_observer_creation": "Error creating observer location: {}",

        # Time Settings
        "time_expander": "⏱️ Time",
        "time_select_label": "Select Time Frame",
        "time_option_now": "Now",
        "time_option_specific": "Specific Night",
        "time_date_select_label": "Select Date for Night:",
        "error_ref_time_creation": "Error setting reference time: {}",
        "info_set_ref_time": "Please ensure a valid date is selected.",

        # Filter Settings
        "filters_expander": "✨ Filters",
        "mag_filter_header": "**Magnitude**",
        "mag_filter_option_bortle": "Bortle Scale",
        "mag_filter_option_manual": "Manual",
        "mag_filter_method_label": "Filter Method:",
        "mag_filter_bortle_label": "Bortle Scale:",
        "mag_filter_bortle_help": "Select Bortle class (1=darkest, 9=brightest city)",
        "mag_filter_min_mag_label": "Min Magnitude:",
        "mag_filter_min_mag_help": "Brightest magnitude limit (lower numbers are brighter)",
        "mag_filter_max_mag_label": "Max Magnitude:",
        "mag_filter_max_mag_help": "Faintest magnitude limit (higher numbers are fainter)",
        "mag_filter_warning_min_max": "Minimum magnitude cannot be greater than maximum magnitude!",
        "min_alt_header": "**Altitude**",
        "min_alt_label": "Minimum Altitude (°):",
        "min_alt_help": "Objects must be above this altitude.",
        "max_alt_label": "Maximum Altitude (°):",
        "max_alt_help": "Objects must be below this altitude (useful for obstructions).",
        "alt_filter_warning_min_max": "Minimum altitude cannot be greater than maximum altitude!",
        "moon_warning_header": "**Moon**",
        "moon_warning_label": "Warn if Moon > (%):",
        "moon_warning_help": "Show a warning in results if moon is brighter than this percentage.",
        "object_types_header": "**Object Types**",
        "object_types_warning_missing_column": "Catalog is missing the 'Type' column.",
        "object_types_error_extract": "Error extracting object types",
        "object_types_label": "Filter by Object Type(s):",
        "object_types_help": "Select specific object types (leave empty for all).",
        "object_types_info_no_types": "No object types available in catalog. Type filter disabled.",
        "size_filter_header": "**Apparent Size**",
        "size_filter_label": "Size Range (arcminutes):",
        "size_filter_help": "Filter objects by their apparent major axis size.",
        "size_filter_error": "Error setting up size slider",
        "size_filter_info_missing": "Size data ('MajAx') missing or invalid in catalog. Size filter disabled.",
        "direction_filter_header": "**Culmination Direction**",
        "direction_option_all": "All Directions",
        "direction_filter_label": "Filter by Direction at Max Altitude:",
        "direction_filter_help": "Show only objects culminating (reaching max altitude) in the selected direction.",

        # Results Options
        "results_options_expander": "⚙️ Results Options",
        "results_options_max_objects_label": "Max Objects to Display:",
        "results_options_max_objects_help": "Limit the number of objects shown in the results list.",
        "results_options_sort_method_label": "Sort Results By:",
        "results_options_sort_duration": "Duration & Altitude",
        "results_options_sort_magnitude": "Brightness (Magnitude)",
        "results_options_sort_method_help": "Choose how to order the found objects.",

        # Main Area: Parameters & Search
        "search_params_header": "Search Parameters Summary",
        "search_params_location_label": "Location:",
        "search_params_time_label": "Time:",
        "search_params_time_now": "Now (Local: {} {})",
        "search_params_time_now_utc": "Now (UTC: {})",
        "search_params_time_specific": "Night of {}",
        "search_params_filter_mag_label": "Magnitude:",
        "search_params_filter_mag_bortle": "Bortle {} (≤ Mag {:.1f})",
        "search_params_filter_mag_bortle_error": "Bortle {} (Limit Error)",
        "search_params_filter_mag_manual": "Manual (Mag {:.1f} to {:.1f})",
        "search_params_filter_alt_label": "Altitude:",
        "search_params_filter_alt_types": "🔭 Alt:{}-{}°, Type:{}",
        "search_params_filter_type_label": "Types:",
        "search_params_types_all": "All",
        "search_params_filter_size_label": "Size:",
        "search_params_filter_size": "📐 Size:{:.1f}′ – {:.1f}′",
        "search_params_filter_direction_label": "Culm. Dir.:",
        "search_params_direction_all": "All",
        "search_params_filter_direction": "🧭 Dir@Max: {}",

        "find_button_label": "🔭 Find Observable Objects",
        "info_initial_prompt": "Please set a valid location in the sidebar to enable search.",
        "spinner_searching": "Searching for observable objects...",
        # --- Correction: Use keyword placeholders ---
        "error_window_unexpected": "Unexpected error calculating observation window: {e}",
        "info_window_calculated": "Observation window: {start_utc} to {end_utc} UTC",
        "info_window_polar_day": "No dark window found (polar day?).",
        "info_window_polar_night": "No clear window found (polar night?).",
        "info_window_polar_night_full": "Permanently dark in window: {start_utc} to {end_utc} UTC",
        "info_window_polar_night_start": "Window: {start_utc} to {end_utc} UTC (polar night starts)",
        "info_window_polar_day_end": "Window: {start_utc} to {end_utc} UTC (polar day ends)",
        "error_no_window": "No valid observation window found.",
        # --- End Correction ---
        "error_cannot_search_no_window": "Cannot perform search without a valid observation window.",
        "warning_window_too_short": "Observation window is very short, results may be limited.",
        "warning_window_too_short_calc": "Observation window is very short. Results based on limited time points.",
        "warning_no_objects_after_filters": "No objects match the selected magnitude, type, or size filters.",
        "warning_no_objects_found_final": "No objects found matching all criteria (including altitude and direction).",
        "success_objects_found": "{} objects found matching criteria.",
        "info_showing_list_duration": "Showing top {} results (sorted by Duration & Altitude).",
        "info_showing_list_magnitude": "Showing top {} results (sorted by Brightness).",
        "error_search_unexpected": "An unexpected error occurred during the search:",
        "error_prereq_catalog": "Error: Catalog data not loaded.",
        "error_prereq_location": "Error: Location is not valid.",
        "error_prereq_time": "Error: Reference time is not valid.",
        "info_no_results_to_display": "No results to display.",

        # Results List & Details
        "results_list_header": "Results",
        "moon_metric_label": "Moon Illumination",
        "moon_warning_message": "Warning: Moon illumination ({:.0f}%) exceeds threshold ({}%)!",
        "moon_phase_error": "Could not calculate moon phase: {}",
        "moon_phase_info_cannot_calc": "Moon phase calculation requires a valid location and time window.",
        "graph_type_label": "Select Plot Type:",
        "graph_type_sky_path": "Sky Path (Polar)",
        "graph_type_alt_time": "Altitude vs. Time",
        "results_expander_title": "{} ({}) - Mag: {}",
        "magnitude_unknown": "N/A",
        "results_details_header": "Details:",
        "results_size_label": "Size:",
        "results_size_value": "{:.1f}′",
        "results_max_alt_header": "Max Altitude:",
        "results_azimuth_label": "(Az:{:.1f}°)",
        "results_direction_label": ", Dir:{}",
        "results_best_time_header": "Best Time (Local):",
        "results_cont_duration_header": "Max Cont. Duration:",
        "results_duration_value": "{:.1f} hours",
        "google_link_text": "Google",
        "simbad_link_text": "SIMBAD",
        "results_graph_button": "📈 Plot",
        "results_spinner_plotting": "Generating plot...",
        "results_close_graph_button": "Close Plot",
        "results_graph_not_created": "Failed to create the plot.",
        "results_save_csv_button": "💾 Download Results as CSV",
        "results_csv_filename": "dso_results_{}.csv",
        "results_csv_export_error": "Error generating CSV file: {}",
        "results_export_name": "Name",
        "results_export_type": "Type",
        "results_export_constellation": "Constellation",
        "results_export_mag": "Magnitude",
        "results_export_size": "Size (arcmin)",
        "results_export_ra": "RA",
        "results_export_dec": "Dec",
        "results_export_max_alt": "Max Altitude (°)",
        "results_export_az_at_max": "Azimuth at Max (°)",
        "results_export_direction_at_max": "Direction at Max",
        "results_export_time_max_utc": "Time at Max (UTC)",
        "results_export_time_max_local": "Time at Max (Local TZ)",
        "results_export_cont_duration": "Max Cont Duration (h)",
        "results_export_redshift": "Redshift (z)",

        # Plotting Errors/Info
        "plot_error_invalid_data_type": "Plot Error: Invalid plot data type provided.",
        "plot_object_default_name": "Object",
        "plot_error_missing_time_alt": "Plot Error: Missing or invalid time/altitude data.",
        "plot_error_missing_azimuth": "Plot Error: Missing or invalid azimuth data required for Sky Path plot.",
        "plot_error_mismatched_lengths": "Plot Error: Time, altitude, and azimuth arrays have mismatched lengths.",
        "plot_error_no_data_points": "Plot Error: Not enough data points to create a plot.",
        "graph_min_altitude_label": "Min Alt ({:.0f}°)",
        "graph_max_altitude_label": "Max Alt ({:.0f}°)",
        "graph_xlabel_time": "Time (UTC)",
        "graph_ylabel_alt": "Altitude (°)",
        "graph_title_alt_time": "Altitude vs. Time: {}",
        "graph_title_sky_path": "Sky Path: {}",
        "graph_colorbar_label": "Time (UTC)",
        "plot_error_unknown_type": "Plot Error: Unknown plot type requested: '{}'",
        "plot_error_unexpected": "Plot Error: An unexpected error occurred during plot creation: {}",

        # Custom Target Section
        "custom_target_expander": "Plot Custom RA/Dec Target",
        "custom_target_ra_label": "Right Ascension (RA):",
        "custom_target_ra_placeholder": "e.g., 10h 08m 22.3s or 10.1395h",
        "custom_target_dec_label": "Declination (Dec):",
        "custom_target_dec_placeholder": "e.g., +11d 58m 02s or 11.9672d",
        "custom_target_name_label": "Target Name (Optional):",
        "custom_target_name_default_placeholder": "Custom Target",
        "custom_target_name_default": "Custom Target",
        "custom_target_button": "Plot Custom Target",
        "custom_target_error_coords_missing": "RA and Dec coordinates are required.",
        "custom_target_error_window_invalid": "Valid location and observation window are required (run a search first).",
        "custom_target_error_window_order": "Observation window start time must be before end time.",
        "custom_target_error_window_short": "Observation window is too short for plotting.",
        "custom_target_error_parsing": "Error parsing coordinates or invalid input:",
        "custom_target_error_unexpected": "Unexpected error plotting custom target:",

        # Cosmology (from Redshift Calculator and expanded)
        "manual_cosmology_expander": "🌌 Manual Cosmology Calculator", # For manual calculator
        "results_cosmology_button": "🌌 Cosmology",
        "cosmology_results_header": "Cosmological Data",
        "cosmology_not_applicable": "Cosmological data not applicable for z ≤ 0.",
        "cosmology_invalid_z": "Invalid redshift value in catalog.",
        "error_module_missing_cosmo": "Error: Function 'calculate_lcdm_distances' not found in 'astro_calculations'.",
        "error_calc_failed_cosmo": "Cosmology calculation failed",
        "redshift_z": "Redshift (z)",
        "redshift_z_tooltip": "Enter the cosmological redshift.",
        "cosmo_params": "Cosmological Parameters",
        "hubble_h0": "Hubble Constant (H₀) [km/s/Mpc]",
        "omega_m": "Matter Density (Ωm)",
        "omega_lambda": "Dark Energy Density (ΩΛ)",
        "flat_universe_warning": "Ωm + ΩΛ ≉ 1. Calculations assume a flat universe (Ωk=0).",
        "results_for": "Results for z = {z:.5f}", # OK with keyword
        "error_invalid_input": "Invalid input. Please use numbers.",
        "error_h0_positive": "Hubble constant must be positive.",
        "error_omega_negative": "Omega parameters cannot be negative.",
        "warn_blueshift": "Warning: Redshift is negative (Blueshift). Cosmological distances are 0 or not directly applicable here.",
        "error_dep_scipy": "Dependency 'scipy' not found. Please install.",
        "error_calc_failed": "Calculation failed: {e}", # OK with keyword
        "warn_integration_accuracy": "Warning: Relative integration accuracy might not be achieved (Error: DC={err_dc:.2e}, LT={err_lt:.2e}).", # OK with keywords
        "lookback_time": "Lookback Time",
        "cosmo_distances": "Cosmological Distances",
        "comoving_distance_title": "**Comoving Distance:**",
        "luminosity_distance_title": "**Luminosity Distance:**",
        "angular_diameter_distance_title": "**Angular Diameter Distance:**",
        "unit_Gyr": "Gyr (Billion Years)",
        "unit_Mpc": "Mpc",
        "unit_Gly": "Gly (Billion Lightyears)",
        "unit_km": "km",
        "unit_km_sci": "km (sci.)",
        "unit_km_full": "km (full)",
        "unit_LJ": "ly",
        "unit_AE": "AU",
        "unit_Ls": "Ls",
        "calculation_note": "Calculation based on the flat ΛCDM model, neglecting radiation density.",
        "example_lookback_recent": "Recently (cosmologically).",
        "example_lookback_humans": "Evolution of modern humans.",
        "example_lookback_dinos": "Age of the dinosaurs.",
        "example_lookback_multicellular": "Emergence of complex life.",
        "example_lookback_earth": "Formation of the Earth.",
        "example_lookback_early_univ": "Early universe.",
        "example_comoving_local": "Local Group.",
        "example_comoving_virgo": "Virgo Cluster.",
        "example_comoving_coma": "Coma Cluster.",
        "example_comoving_lss": "Large-scale structures.",
        "example_comoving_quasars": "Distant quasars.",
        "example_comoving_cmb": "'Edge' of observable universe (CMB).",
        "explanation_luminosity": "Relevant for brightness (standard candles).",
        "explanation_angular": "Relevant for size (standard rulers).",

        # Donation Link
        "donation_button_text": "Support Development via Ko-fi ☕",
    },
    # --- Französische Übersetzungen ---
    'FR': {
        # App Général
        "app_title": "Advanced DSO Finder",
        "lang_select": "Choisir la langue",
        "settings_header": "Paramètres",
        "bug_report": "Trouvé un bug ou des commentaires ?",
        "bug_report_button": "🐞 Signaler un problème / Suggestion",
        "bug_report_subject": "Rapport de bug/Commentaire : Advanced DSO Finder",
        "bug_report_body": "Veuillez décrire le problème ou la suggestion :\n\n(Inclure les étapes pour reproduire si c'est un bug)\n\nVersion/Date de l'app : [Si connu]\nNavigateur/OS : [Si pertinent]",
        "error_module_missing": "Erreur : Module manquant :",
        "error_unexpected": "Erreur inattendue :",

        # Catalogue & Chargement
        "info_catalog_loaded": "Catalogue chargé : {} objets.",
        "error_catalog_load_failed": "Échec du chargement du catalogue. Vérifier le fichier.",
        "error_catalog_not_found": "Erreur : Fichier catalogue introuvable au chemin :",
        "info_catalog_missing": "Données du catalogue non chargées. Recherche désactivée.",

        # Glossaire
        "object_type_glossary_title": "Glossaire des types d'objets",
        "glossary_unavailable": "Glossaire non disponible pour la langue sélectionnée.",
        "object_type_glossary": {
            "G": "Galaxie", "OC": "Amas Ouvert", "GC": "Amas Globulaire", "PN": "Nébuleuse Planétaire",
            "DN": "Nébuleuse Sombre", "BN": "Nébuleuse Brillante", "SNR": "Rémanent de Supernova", "C+N": "Amas avec Nébuleuse",
            "Ast": "Astérisme", "Kt": "Nœud dans Galaxie", "Dup": "Doublon", "NonEx": "Non-Existant",
        },

        # Paramètres de localisation
        "location_expander": "📍 Localisation",
        "location_select_label": "Méthode de localisation",
        "location_option_search": "Recherche",
        "location_option_manual": "Manuelle",
        "location_lat_label": "Latitude (°N)",
        "location_lon_label": "Longitude (°E)",
        "location_elev_label": "Altitude (m)",
        "location_error_manual_invalid": "Coordonnées ou altitude manuelles invalides.",
        "location_search_label": "Rechercher Lieu/Adresse :",
        "location_search_placeholder": "ex: Paris, France ou Code Postal",
        "location_search_submit_button": "Trouver Coordonnées",
        "spinner_geocoding": "Recherche de localisation...",
        "location_search_info_fallback": "Échec Nominatim, essai ArcGIS...",
        "location_search_info_fallback2": "Échec ArcGIS, essai Photon...",
        "location_search_coords": "Lat:{:.4f}, Lon:{:.4f}",
        "location_search_found": "Trouvé (N): {}",
        "location_search_found_fallback": "Trouvé (A): {}",
        "location_search_found_fallback2": "Trouvé (P): {}",
        "location_search_error_timeout": "Délai d'attente dépassé pour le géocodage.",
        "location_search_error_service": "Erreur du service de géocodage : {}",
        "location_search_error_fallback2_failed": "Échec de tous les services de géocodage : {}",
        "location_search_error_not_found": "Localisation non trouvée.",
        "timezone_auto_set_label": "Fuseau horaire détecté :",
        "timezone_auto_fail_label": "Fuseau horaire :",
        "timezone_auto_fail_msg": "Détection échouée",
        "timezone_auto_fail_invalid_label": "Fuseau horaire :",
        "timezone_auto_fail_invalid_msg": "Nom invalide :",
        "timezone_auto_fail_error_label": "Fuseau horaire :",
        "timezone_auto_fail_error_msg": "Erreur",
        "timezone_finder_unavailable_label": "Fuseau horaire :",
        "timezone_finder_unavailable_msg": "Finder N/D",
        "timezone_invalid_location_label": "Fuseau horaire :",
        "timezone_invalid_location_msg": "Localisation Invalide",
        "location_not_set": "Localisation non définie ou invalide.",
        "location_manual_display": "Manuelle ({:.4f}°N, {:.4f}°E)",
        "location_search_display": "Recherché : {} ({:.4f}°N, {:.4f}°E)",
        "location_invalid_for_run": "Localisation Invalide",
        "error_observer_creation": "Erreur lors de la création de la localisation de l'observateur : {}",

        # Paramètres de temps
        "time_expander": "⏱️ Temps",
        "time_select_label": "Choisir période",
        "time_option_now": "Maintenant",
        "time_option_specific": "Nuit Spécifique",
        "time_date_select_label": "Choisir date pour la nuit :",
        "error_ref_time_creation": "Erreur lors de la définition du temps de référence : {}",
        "info_set_ref_time": "Veuillez assurer qu'une date valide est sélectionnée.",

        # Paramètres de filtre
        "filters_expander": "✨ Filtres",
        "mag_filter_header": "**Magnitude**",
        "mag_filter_option_bortle": "Échelle de Bortle",
        "mag_filter_option_manual": "Manuelle",
        "mag_filter_method_label": "Méthode de filtrage :",
        "mag_filter_bortle_label": "Échelle de Bortle :",
        "mag_filter_bortle_help": "Choisir classe Bortle (1=sombre, 9=ville)",
        "mag_filter_min_mag_label": "Magnitude Min :",
        "mag_filter_min_mag_help": "Limite de magnitude la plus brillante (petits chiffres = brillant)",
        "mag_filter_max_mag_label": "Magnitude Max :",
        "mag_filter_max_mag_help": "Limite de magnitude la plus faible (grands chiffres = faible)",
        "mag_filter_warning_min_max": "Magnitude minimum ne peut pas être supérieure à maximum !",
        "min_alt_header": "**Altitude**",
        "min_alt_label": "Altitude Minimum (°):",
        "min_alt_help": "Les objets doivent être au-dessus de cette altitude.",
        "max_alt_label": "Altitude Maximum (°):",
        "max_alt_help": "Les objets doivent être en dessous de cette altitude (utile pour obstructions).",
        "alt_filter_warning_min_max": "Altitude minimum ne peut pas être supérieure à maximum !",
        "moon_warning_header": "**Lune**",
        "moon_warning_label": "Avertir si Lune > (%):",
        "moon_warning_help": "Montrer un avertissement si la lune est plus brillante que ce pourcentage.",
        "object_types_header": "**Types d'objets**",
        "object_types_warning_missing_column": "La colonne 'Type' manque dans le catalogue.",
        "object_types_error_extract": "Erreur lors de l'extraction des types d'objets",
        "object_types_label": "Filtrer par Type(s) d'objet :",
        "object_types_help": "Choisir types spécifiques (laisser vide pour tous).",
        "object_types_info_no_types": "Aucun type d'objet disponible. Filtre désactivé.",
        "size_filter_header": "**Taille Apparente**",
        "size_filter_label": "Plage de Taille (arcmin):",
        "size_filter_help": "Filtrer par taille apparente de l'axe majeur.",
        "size_filter_error": "Erreur de configuration du curseur de taille",
        "size_filter_info_missing": "Données de taille ('MajAx') manquantes. Filtre désactivé.",
        "direction_filter_header": "**Direction de Culmination**",
        "direction_option_all": "Toutes Directions",
        "direction_filter_label": "Filtrer par Direction à Altitude Max :",
        "direction_filter_help": "Montrer seulement les objets culminant dans la direction choisie.",

        # Options de Résultats
        "results_options_expander": "⚙️ Options des Résultats",
        "results_options_max_objects_label": "Max Objets à Afficher :",
        "results_options_max_objects_help": "Limite le nombre d'objets dans la liste de résultats.",
        "results_options_sort_method_label": "Trier Résultats Par :",
        "results_options_sort_duration": "Durée & Altitude",
        "results_options_sort_magnitude": "Luminosité (Magnitude)",
        "results_options_sort_method_help": "Choisir l'ordre de tri des objets trouvés.",

        # Zone Principale : Paramètres & Recherche
        "search_params_header": "Résumé des Paramètres de Recherche",
        "search_params_location_label": "Localisation :",
        "search_params_time_label": "Temps :",
        "search_params_time_now": "Maintenant (Local: {} {})",
        "search_params_time_now_utc": "Maintenant (UTC: {})",
        "search_params_time_specific": "Nuit du {}",
        "search_params_filter_mag_label": "Magnitude :",
        "search_params_filter_mag_bortle": "Bortle {} (≤ Mag {:.1f})",
        "search_params_filter_mag_bortle_error": "Bortle {} (Erreur Limite)",
        "search_params_filter_mag_manual": "Manuelle (Mag {:.1f} à {:.1f})",
        "search_params_filter_alt_label": "Altitude :",
        "search_params_filter_alt_types": "🔭 Alt:{}-{}°, Type:{}",
        "search_params_filter_type_label": "Types :",
        "search_params_types_all": "Tous",
        "search_params_filter_size_label": "Taille :",
        "search_params_filter_size": "📐 Taille:{:.1f}′ – {:.1f}′",
        "search_params_filter_direction_label": "Dir. Culm. :",
        "search_params_direction_all": "Toutes",
        "search_params_filter_direction": "🧭 Dir@Max: {}",

        "find_button_label": "🔭 Trouver Objets Observables",
        "info_initial_prompt": "Veuillez définir une localisation valide dans la barre latérale pour activer la recherche.",
        "spinner_searching": "Recherche d'objets observables...",
        # --- Correction: Use keyword placeholders ---
        "error_window_unexpected": "Erreur inattendue lors du calcul de la fenêtre : {e}",
        "info_window_calculated": "Fenêtre d'observation : {start_utc} à {end_utc} UTC",
        "info_window_polar_day": "Pas de fenêtre sombre trouvée (jour polaire ?).",
        "info_window_polar_night": "Pas de fenêtre claire trouvée (nuit polaire ?).",
        "info_window_polar_night_full": "Nuit permanente dans la fenêtre : {start_utc} à {end_utc} UTC",
        "info_window_polar_night_start": "Fenêtre : {start_utc} à {end_utc} UTC (début nuit polaire)",
        "info_window_polar_day_end": "Fenêtre : {start_utc} à {end_utc} UTC (fin jour polaire)",
        "error_no_window": "Aucune fenêtre d'observation valide trouvée.",
        # --- End Correction ---
        "error_cannot_search_no_window": "Recherche impossible sans fenêtre d'observation valide.",
        "warning_window_too_short": "Fenêtre d'observation très courte, résultats limités.",
        "warning_window_too_short_calc": "Fenêtre d'observation très courte. Résultats basés sur peu de points temporels.",
        "warning_no_objects_after_filters": "Aucun objet ne correspond aux filtres de magnitude, type ou taille.",
        "warning_no_objects_found_final": "Aucun objet trouvé correspondant à tous les critères (incl. altitude/direction).",
        "success_objects_found": "{} objets trouvés correspondant aux critères.",
        "info_showing_list_duration": "Affichage des {} meilleurs résultats (triés par Durée & Altitude).",
        "info_showing_list_magnitude": "Affichage des {} meilleurs résultats (triés par Luminosité).",
        "error_search_unexpected": "Une erreur inattendue s'est produite pendant la recherche :",
        "error_prereq_catalog": "Erreur : Données du catalogue non chargées.",
        "error_prereq_location": "Erreur : Localisation invalide.",
        "error_prereq_time": "Erreur : Temps de référence invalide.",
        "info_no_results_to_display": "Aucun résultat à afficher.",

        # Liste de Résultats & Détails
        "results_list_header": "Résultats",
        "moon_metric_label": "Illumination Lunaire",
        "moon_warning_message": "Avertissement : Illumination lunaire ({:.0f}%) dépasse le seuil ({}%) !",
        "moon_phase_error": "Impossible de calculer la phase lunaire : {}",
        "moon_phase_info_cannot_calc": "Calcul de phase lunaire nécessite localisation et fenêtre temporelle valides.",
        "graph_type_label": "Choisir Type de Graphique :",
        "graph_type_sky_path": "Trajectoire Céleste (Polaire)",
        "graph_type_alt_time": "Altitude vs. Temps",
        "results_expander_title": "{} ({}) - Mag: {}",
        "magnitude_unknown": "N/D",
        "results_details_header": "Détails :",
        "results_size_label": "Taille :",
        "results_size_value": "{:.1f}′",
        "results_max_alt_header": "Altitude Max :",
        "results_azimuth_label": "(Az:{:.1f}°)",
        "results_direction_label": ", Dir:{}",
        "results_best_time_header": "Meilleur Moment (Local) :",
        "results_cont_duration_header": "Durée Cont. Max :",
        "results_duration_value": "{:.1f} heures",
        "google_link_text": "Google",
        "simbad_link_text": "SIMBAD",
        "results_graph_button": "📈 Graphique",
        "results_spinner_plotting": "Génération du graphique...",
        "results_close_graph_button": "Fermer Graphique",
        "results_graph_not_created": "Échec de la création du graphique.",
        "results_save_csv_button": "💾 Télécharger Résultats en CSV",
        "results_csv_filename": "dso_resultats_{}.csv",
        "results_csv_export_error": "Erreur lors de la génération du fichier CSV : {}",
        "results_export_name": "Nom",
        "results_export_type": "Type",
        "results_export_constellation": "Constellation",
        "results_export_mag": "Magnitude",
        "results_export_size": "Taille (arcmin)",
        "results_export_ra": "AD", # Ascension Droite
        "results_export_dec": "Dec", # Déclinaison
        "results_export_max_alt": "Altitude Max (°)",
        "results_export_az_at_max": "Azimut à Max (°)",
        "results_export_direction_at_max": "Direction à Max",
        "results_export_time_max_utc": "Temps à Max (UTC)",
        "results_export_time_max_local": "Temps à Max (Local)",
        "results_export_cont_duration": "Durée Cont Max (h)",
        "results_export_redshift": "Décalage Rouge (z)",

        # Erreurs/Infos Plotting
        "plot_error_invalid_data_type": "Erreur Graphique : Type de données invalide.",
        "plot_object_default_name": "Objet",
        "plot_error_missing_time_alt": "Erreur Graphique : Données temps/altitude manquantes ou invalides.",
        "plot_error_missing_azimuth": "Erreur Graphique : Données azimut manquantes pour trajectoire céleste.",
        "plot_error_mismatched_lengths": "Erreur Graphique : Longueurs de tableaux temps/altitude/azimut différentes.",
        "plot_error_no_data_points": "Erreur Graphique : Pas assez de points de données pour graphique.",
        "graph_min_altitude_label": "Alt Min ({:.0f}°)",
        "graph_max_altitude_label": "Alt Max ({:.0f}°)",
        "graph_xlabel_time": "Temps (UTC)",
        "graph_ylabel_alt": "Altitude (°)",
        "graph_title_alt_time": "Altitude vs. Temps : {}",
        "graph_title_sky_path": "Trajectoire Céleste : {}",
        "graph_colorbar_label": "Temps (UTC)",
        "plot_error_unknown_type": "Erreur Graphique : Type de graphique inconnu : '{}'",
        "plot_error_unexpected": "Erreur Graphique : Erreur inattendue lors de la création : {}",

        # Section Cible Personnalisée
        "custom_target_expander": "Tracer Cible AD/Dec Personnalisée",
        "custom_target_ra_label": "Ascension Droite (AD) :",
        "custom_target_ra_placeholder": "ex: 10h 08m 22.3s ou 10.1395h",
        "custom_target_dec_label": "Déclinaison (Dec) :",
        "custom_target_dec_placeholder": "ex: +11d 58m 02s ou 11.9672d",
        "custom_target_name_label": "Nom Cible (Optionnel) :",
        "custom_target_name_default_placeholder": "Cible Personnalisée",
        "custom_target_name_default": "Cible Personnalisée",
        "custom_target_button": "Tracer Cible Personnalisée",
        "custom_target_error_coords_missing": "Coordonnées AD et Dec requises.",
        "custom_target_error_window_invalid": "Localisation et fenêtre d'observation valides requises (lancer une recherche d'abord).",
        "custom_target_error_window_order": "Heure de début de fenêtre doit être avant heure de fin.",
        "custom_target_error_window_short": "Fenêtre d'observation trop courte pour tracer.",
        "custom_target_error_parsing": "Erreur d'analyse des coordonnées :",
        "custom_target_error_unexpected": "Erreur inattendue lors du tracé :",

        # Cosmologie
        "manual_cosmology_expander": "🌌 Calculateur Cosmologique Manuel", # Pour manuellen Rechner
        "results_cosmology_button": "🌌 Cosmologie",
        "cosmology_results_header": "Données Cosmologiques",
        "cosmology_not_applicable": "Données cosmologiques non applicables pour z ≤ 0.",
        "cosmology_invalid_z": "Valeur de décalage vers le rouge invalide dans le catalogue.",
        "error_module_missing_cosmo": "Erreur : Fonction 'calculate_lcdm_distances' introuvable dans 'astro_calculations'.",
        "error_calc_failed_cosmo": "Échec du calcul cosmologique",
        "redshift_z": "Décalage vers le rouge (z)",
        "redshift_z_tooltip": "Entrer le décalage cosmologique vers le rouge.",
        "cosmo_params": "Paramètres Cosmologiques",
        "hubble_h0": "Constante de Hubble (H₀) [km/s/Mpc]",
        "omega_m": "Densité de matière (Ωm)",
        "omega_lambda": "Densité d'énergie noire (ΩΛ)",
        "flat_universe_warning": "Ωm + ΩΛ ≉ 1. Calculs supposent univers plat (Ωk=0).",
        "results_for": "Résultats pour z = {z:.5f}", # OK with keyword
        "error_invalid_input": "Entrée invalide. Veuillez utiliser des chiffres.",
        "error_h0_positive": "Constante de Hubble doit être positive.",
        "error_omega_negative": "Paramètres Omega ne peuvent être négatifs.",
        "warn_blueshift": "Avertissement : Décalage vers le rouge négatif (Blueshift). Distances cosmologiques sont 0 ou non applicables.",
        "error_dep_scipy": "Dépendance 'scipy' introuvable. Veuillez l'installer.",
        "error_calc_failed": "Le calcul a échoué : {e}", # OK with keyword
        "warn_integration_accuracy": "Avertissement : Précision relative d'intégration potentiellement non atteinte (Erreur : DC={err_dc:.2e}, LT={err_lt:.2e}).", # OK with keywords
        "lookback_time": "Temps de regard en arrière",
        "cosmo_distances": "Distances Cosmologiques",
        "comoving_distance_title": "**Distance comobile :**",
        "luminosity_distance_title": "**Distance de luminosité :**",
        "angular_diameter_distance_title": "**Distance de diamètre angulaire :**",
        "unit_Gyr": "Ga (Milliards d'années)",
        "unit_Mpc": "Mpc",
        "unit_Gly": "Gal (Milliards d'années-lumière)",
        "unit_km": "km",
        "unit_km_sci": "km (sci.)",
        "unit_km_full": "km (complet)",
        "unit_LJ": "al", # année-lumière
        "unit_AE": "UA", # Unité Astronomique
        "unit_Ls": "sl", # seconde-lumière
        "calculation_note": "Calcul basé sur modèle ΛCDM plat (densité de rayonnement négligée).",
        "example_lookback_recent": "Récemment (cosmologiquement).",
        "example_lookback_humans": "Évolution humains modernes.",
        "example_lookback_dinos": "Ère des dinosaures.",
        "example_lookback_multicellular": "Apparition vie complexe.",
        "example_lookback_earth": "Formation de la Terre.",
        "example_lookback_early_univ": "Univers primordial.",
        "example_comoving_local": "Groupe Local.",
        "example_comoving_virgo": "Amas de la Vierge.",
        "example_comoving_coma": "Amas de Coma.",
        "example_comoving_lss": "Grandes structures.",
        "example_comoving_quasars": "Quasars lointains.",
        "example_comoving_cmb": "'Bord' de l'univers observable (FDC).",
        "explanation_luminosity": "Pertinent pour luminosité (chandelles standard).",
        "explanation_angular": "Pertinent pour taille (règles standard).",

        # Lien Donation
        "donation_button_text": "Soutenir le développement via Ko-fi ☕",
    },
}


# --- Glossar Daten (aus Redshift Calculator) ---
# Enthält Erklärungen für kosmologische Begriffe.
glossary_data = {
    'DE': {
        "Rotverschiebung (z)": "Ein Maß dafür, wie stark sich das Licht von entfernten Objekten aufgrund der Expansion des Universums zum roten Ende des Spektrums verschoben hat. Höhere z-Werte bedeuten größere Entfernungen und frühere Zeiten im Universum.",
        "Hubble-Konstante (H₀)": "Die Rate, mit der das Universum heute expandiert, typischerweise angegeben in km/s pro Megaparsec (Mpc). Sie verknüpft die Entfernung eines Objekts mit seiner scheinbaren Rückzugsgeschwindigkeit.",
        "Materiedichte (Ωm)": "Der Anteil der Gesamtenergiedichte des Universums, der auf Materie (sowohl normale baryonische Materie als auch Dunkle Materie) entfällt.",
        "Dunkle Energie (ΩΛ)": "Der Anteil der Gesamtenergiedichte des Universums, der auf Dunkle Energie entfällt, die für die beschleunigte Expansion des Universums verantwortlich gemacht wird.",
        "Mitbewegte Distanz": "Eine Distanzmessung, die den Effekt der Expansion des Universums herausrechnet. Sie repräsentiert die Entfernung zwischen zwei Objekten zu einem bestimmten Zeitpunkt (z.B. heute), wenn sie sich nur aufgrund der Hubble-Expansion bewegen.",
        "Leuchtkraftdistanz": "Eine Distanzmessung, die verwendet wird, um die beobachtete Helligkeit eines Objekts mit seiner tatsächlichen (intrinsischen) Leuchtkraft in Beziehung zu setzen. Sie ist größer als die mitbewegte Distanz bei z > 0.",
        "Winkeldurchmesserdistanz": "Eine Distanzmessung, die verwendet wird, um die beobachtete Winkelgröße eines Objekts mit seiner tatsächlichen physikalischen Größe in Beziehung zu setzen. Interessanterweise nimmt sie ab z ≈ 1.6 wieder zu.",
        "Rückblickzeit": "Die Zeitspanne, die das Licht von einem entfernten Objekt benötigt hat, um uns zu erreichen. Es ist das Alter des Universums, als das Licht ausgesandt wurde, abgezogen vom heutigen Alter des Universums.",
        "Mpc (Megaparsec)": "Eine astronomische Entfernungseinheit, die etwa 3.26 Millionen Lichtjahren entspricht.",
        "Gly/Gyr (Gigalichtjahr/Gigajahr)": "Eine Milliarde (10⁹) Lichtjahre bzw. Jahre.",
    },
    'EN': {
        "Redshift (z)": "A measure of how much the light from distant objects has been stretched towards the red end of the spectrum due to the expansion of the universe. Higher z values mean greater distances and earlier times in the universe.",
        "Hubble Constant (H₀)": "The rate at which the universe is expanding today, typically given in km/s per Megaparsec (Mpc). It relates an object's distance to its apparent recession velocity.",
        "Matter Density (Ωm)": "The fraction of the total energy density of the universe attributed to matter (both normal baryonic matter and dark matter).",
        "Dark Energy Density (ΩΛ)": "The fraction of the total energy density of the universe attributed to dark energy, which is responsible for the accelerated expansion of the universe.",
        "Comoving Distance": "A distance measure that factors out the expansion of the universe. It represents the distance between two objects at a specific time (e.g., today) if they were only moving due to Hubble expansion.",
        "Luminosity Distance": "A distance measure used to relate the observed brightness (flux) of an object to its actual (intrinsic) luminosity. It is larger than the comoving distance for z > 0.",
        "Angular Diameter Distance": "A distance measure used to relate the observed angular size of an object to its actual physical size. Interestingly, it decreases again beyond z ≈ 1.6.",
        "Lookback Time": "The amount of time the light from a distant object has traveled to reach us. It's the age of the universe when the light was emitted subtracted from the age of the universe today.",
        "Mpc (Megaparsec)": "An astronomical unit of distance equal to about 3.26 million light-years.",
        "Gly/Gyr (Gigalightyear/Gigayear)": "One billion (10⁹) light-years or years, respectively.",
    },
    'FR': {
        "Décalage vers le rouge (z)": "Mesure de l'étirement de la lumière des objets distants vers l'extrémité rouge du spectre en raison de l'expansion de l'univers. Des valeurs de z plus élevées signifient des distances plus grandes et des temps plus reculés dans l'univers.",
        "Constante de Hubble (H₀)": "Le taux d'expansion actuel de l'univers, généralement exprimé en km/s par Mégaparsec (Mpc). Elle relie la distance d'un objet à sa vitesse de récession apparente.",
        "Densité de matière (Ωm)": "La fraction de la densité d'énergie totale de l'univers attribuée à la matière (matière baryonique normale et matière noire).",
        "Densité d'énergie noire (ΩΛ)": "La fraction de la densité d'énergie totale de l'univers attribuée à l'énergie noire, responsable de l'expansion accélérée de l'univers.",
        "Distance comobile": "Mesure de distance qui élimine l'effet de l'expansion de l'univers. Elle représente la distance entre deux objets à un moment précis (par exemple, aujourd'hui) s'ils ne se déplaçaient qu'en raison de l'expansion de Hubble.",
        "Distance de luminosité": "Mesure de distance utilisée pour relier la luminosité observée (flux) d'un objet à sa luminosité réelle (intrinsèque). Elle est plus grande que la distance comobile pour z > 0.",
        "Distance de diamètre angulaire": "Mesure de distance utilisée pour relier la taille angulaire observée d'un objet à sa taille physique réelle. Curieusement, elle diminue à nouveau au-delà de z ≈ 1.6.",
        "Temps de regard en arrière": "Le temps que la lumière d'un objet distant a mis pour nous parvenir. C'est l'âge de l'univers au moment où la lumière a été émise, soustrait de l'âge actuel de l'univers.",
        "Mpc (Mégaparsec)": "Unité de distance astronomique équivalant à environ 3,26 millions d'années-lumière.",
        "Gal/Ga (Giga-année-lumière/Giga-année)": "Un milliard (10⁹) d'années-lumière ou d'années, respectivement.",
    }
}
